title: Ladybridge Singers
tagline: 

author:
  name: Ladybridge Singers
  url: 
  
twitter:
  username: 

defaults:
  - scope:
      path: ""      
      type: "posts"
    values:
      author: 
      image: "apple-touch-icon.png"
  - scope:
      path: ""      
      type: "pages"
    values:
      author: 
      image: "apple-touch-icon.png"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

remote_theme: zivong/jekyll-theme-hydure

paginate: 10

disqus: 
google_analytics: 

tags_path: /tags/
categories_path: /categories/
