title: Zivong's Blog
tagline: Record what I read, think and do

author:
  name: Song-Zi Vong
  url: https://twitter.com/zivong91

twitter:
  username: zivong91

defaults:
  - scope:
      path: ""      
      type: "posts"
    values:
      author: "Song-Zi Vong"
      image: "apple-touch-icon.png"
  - scope:
      path: ""      
      type: "pages"
    values:
      author: "Song-Zi Vong"
      image: "apple-touch-icon.png"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

remote_theme: zivong/jekyll-theme-hydure

paginate: 10

disqus: zivong
google_analytics: G-DBXE19KQCJ
